services:
  # 백엔드 API 서버
  backend:
    image: nasir17/yakjeong:be-v1
    container_name: yakjeong_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/yakjeong.db
      - PYTHONPATH=/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 프론트엔드 개발 서버
  frontend:
    image: nasir17/yakjeong:fe-v1
    container_name: yakjeong_frontend
    ports:
      - "40000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      backend:
        condition: service_healthy
    command: npm run dev

volumes:
  backend_data:
